sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.decorators.cache import cache_page

from sitewomen import settings
from women.sitemaps import PostSitemap, CategorySitemap

sitemaps = {
    'posts': PostSitemap,
    'cat': CategorySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Известные женщины мира'

sitewomen/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views
from .apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUserView.as_view(), name='profile'),

    path('passwoed-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

sitewomen/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/%m/%d', **NULLABLE, verbose_name='Фотография')
    date_birth = models.DateTimeField(**NULLABLE, verbose_name='Дата рождения')

sitewomen/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class MixinWidgets:

    class Meta:
        widgets = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        widgets = self.Meta.widgets
        if widgets:
            for field_name, widget in widgets.items():
                self.fields[field_name].widget = widget


class UserLoginForm(MixinWidgets, AuthenticationForm):
    username = forms.CharField(label='Логин/E-mail')
    password = forms.CharField(label='Пароль')

    class Meta:
        model = get_user_model()
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш логин'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ваш пароль'}),
        }


class RegisterUserForm(MixinWidgets, UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль')
    password2 = forms.CharField(label='Повтор пароля')

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Придумайте пароль'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите пароль'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким E-mail уже существует')
        return email


class ProfileUserForm(MixinWidgets, forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин')
    email = forms.CharField(disabled=True, required=False, label='E-mail')

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'date_birth': 'Дата рождения',
        }
        this_year = datetime.date.today().year
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'date_birth': forms.SelectDateWidget(years=range(this_year - 100, this_year - 5),
                                                 attrs={'class': 'form-control'}),
        }


class UserPasswordChangeForm(MixinWidgets, PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль')
    new_password1 = forms.CharField(label='Новый пароль')
    new_password2 = forms.CharField(label='Подтверждение пароля')

    class Meta:
        widgets = {
            'old_password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

sitewomen/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from sitewomen import settings
from users.forms import UserLoginForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUserView(LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Авторизация',
        'button': 'Войти',
    }


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    extra_context = {
        'title': 'Регистрация',
        'button': 'Зарегистрироваться',
    }


class ProfileUserView(LoginRequiredMixin, UpdateView):
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': 'Профиль пользователя',
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    """ Для отображения формы изменения пароля у авторизованного пользователя """

    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')
    extra_context = {
        'title': 'Изменение пароля',
        'button': 'Сохранить',
    }


class UserPasswordChangeDoneView(PasswordChangeDoneView):
    """ Для отображения страницы успешного изменения пароля у авторизованного пользователя """

    template_name = 'users/password_change_done.html'
    extra_context = {
        'title': 'Ваш пароль был успешно изменен!',
        'button': 'Вернуться в профиль',
    }


class UserPasswordResetView(PasswordResetView):
    """ Для отображения формы ввода E-mail адреса при восстановлении пароля """

    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    extra_context = {
        'title': 'Восстановление пароля',
        'button': 'Сбросить по E-mail',
    }


class UserPasswordResetDoneView(PasswordResetDoneView):
    """ Для отображения страницы сброса на E-mail инструкций восстановления пароля """

    template_name = 'users/password_reset_done.html'
    extra_context = {
        'title': 'Сброс пароля',
    }


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """ Для отображения формы создания нового пароля (при его восстановлении) """

    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')
    extra_context = {
        'title': 'Новый пароль',
        'button': 'Сохранить',
    }


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    """ Для отображения страницы успешности изменения пароля (при его восстановлении) """

    template_name = 'users/password_reset_complete.html'
    extra_context = {
        'title': 'Восстановление пароля завершено',
    }

sitewomen/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p>
            <button type="submit">{{ button }}</button>
        </p>
        <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
    </form>

    <hr>
    <p><a href="{% url 'social:begin' 'github' %}">Войти через GitHub</a></p>

{% endblock %}

sitewomen/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p><a href="{% url 'users:profile' %}">{{ button }}</a></p>
{% endblock %}

sitewomen/users/templates/users/password_change_form.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{ title }}</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">{{ button }}</button></p>
</form>
 
{% endblock %}

sitewomen/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}"><strong>входа в систему</strong></a>.</p>

{% endblock %}

sitewomen/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form action="" method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">{{ button }}</button></p>
    </form>

{% endblock %}

sitewomen/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{{ title }}</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

sitewomen/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

sitewomen/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form method="post">
        {% csrf_token %}

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">{{ button }}</button></p>
    </form>

{% endblock %}

sitewomen/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user.photo %}
            <p><img src="{{ user.photo.url }}"></p>
        {% else %}
            <p><img src="{{ default_image }}"></p>
        {% endif %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p>
            <button type="submit">Сохранить</button>
        </p>
    </form>

    {% if not perms.users.social_auth %}
        <br>
        <p><a href="{% url 'users:password_change' %}">Изменить пароль</a></p>
    {% endif %}

{% endblock %}

sitewomen/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">{{ button }}</button></p>
    </form>

{% endblock %}

sitewomen/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
    <h1>Регистрация прошла успешно!</h1>
    <p>Вы успешно зарегестрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a
            href="{% url 'users:login' %}">ссылке</a></p>
{% endblock %}